# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from spawn.v1 import spawn_control_pb2 as spawn_dot_v1_dot_spawn__control__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in spawn/v1/spawn_control_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SpawnControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/spawn.v1.SpawnControl/Health",
            request_serializer=spawn_dot_v1_dot_spawn__control__pb2.HealthRequest.SerializeToString,
            response_deserializer=spawn_dot_v1_dot_spawn__control__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.CodexSessionRefresh = channel.unary_unary(
            "/spawn.v1.SpawnControl/CodexSessionRefresh",
            request_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshRequest.SerializeToString,
            response_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshResponse.FromString,
            _registered_method=True,
        )
        self.CodexSessionStatus = channel.unary_unary(
            "/spawn.v1.SpawnControl/CodexSessionStatus",
            request_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusRequest.SerializeToString,
            response_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusResponse.FromString,
            _registered_method=True,
        )
        self.CodexSessionLogs = channel.unary_unary(
            "/spawn.v1.SpawnControl/CodexSessionLogs",
            request_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsRequest.SerializeToString,
            response_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsResponse.FromString,
            _registered_method=True,
        )
        self.CodexSessionList = channel.unary_unary(
            "/spawn.v1.SpawnControl/CodexSessionList",
            request_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListRequest.SerializeToString,
            response_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListResponse.FromString,
            _registered_method=True,
        )


class SpawnControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CodexSessionRefresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CodexSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CodexSessionLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CodexSessionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpawnControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=spawn_dot_v1_dot_spawn__control__pb2.HealthRequest.FromString,
            response_serializer=spawn_dot_v1_dot_spawn__control__pb2.HealthResponse.SerializeToString,
        ),
        "CodexSessionRefresh": grpc.unary_unary_rpc_method_handler(
            servicer.CodexSessionRefresh,
            request_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshRequest.FromString,
            response_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshResponse.SerializeToString,
        ),
        "CodexSessionStatus": grpc.unary_unary_rpc_method_handler(
            servicer.CodexSessionStatus,
            request_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusRequest.FromString,
            response_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusResponse.SerializeToString,
        ),
        "CodexSessionLogs": grpc.unary_unary_rpc_method_handler(
            servicer.CodexSessionLogs,
            request_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsRequest.FromString,
            response_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsResponse.SerializeToString,
        ),
        "CodexSessionList": grpc.unary_unary_rpc_method_handler(
            servicer.CodexSessionList,
            request_deserializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListRequest.FromString,
            response_serializer=spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "spawn.v1.SpawnControl", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("spawn.v1.SpawnControl", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SpawnControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spawn.v1.SpawnControl/Health",
            spawn_dot_v1_dot_spawn__control__pb2.HealthRequest.SerializeToString,
            spawn_dot_v1_dot_spawn__control__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CodexSessionRefresh(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spawn.v1.SpawnControl/CodexSessionRefresh",
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshRequest.SerializeToString,
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionRefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CodexSessionStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spawn.v1.SpawnControl/CodexSessionStatus",
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusRequest.SerializeToString,
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CodexSessionLogs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spawn.v1.SpawnControl/CodexSessionLogs",
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsRequest.SerializeToString,
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CodexSessionList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/spawn.v1.SpawnControl/CodexSessionList",
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListRequest.SerializeToString,
            spawn_dot_v1_dot_spawn__control__pb2.CodexSessionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
